on:
  push:
    branches:
      - main
      - master
env:
  RENV_PATHS_ROOT: ~/.local/share/renv

name: renderbook

jobs:
  bookdown:
    runs-on:  ubuntu-20.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v1

      - name: Install pandoc
        uses: r-lib/actions/setup-pandoc@v1

      - name: Install Linux system dependencies
        run: |
          # install spatial dependencies
          sudo apt update
          sudo apt install \
            libudunits2-dev \
            libgdal-dev \
            gdal-bin \
            libgeos-dev \
            libproj-dev \
            libcairo2-dev

      - name: Decrypt GCP key
        run: ./.github/workflows/secrets/decrypt_secret.sh
        env:
          GCP_ENCRYPT_PASSPHRASE: ${{ secrets.GCP_ENCRYPT_PASSPHRASE }}
      
      - name: Cache Renv packages
        uses: actions/cache@v1
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: Cache bookdown results
        uses: actions/cache@v2
        with:
          path: _bookdown_files
          key: bookdown-${{ hashFiles('**/*Rmd') }}
          restore-keys: |
            ${{ runner.os }}-bookdown-
          
      - name: Restore packages
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()

      - name: Build book
        run: Rscript -e 'bookdown::render_book("index.Rmd", quiet = TRUE)'
        env:
          CENSUS_API_KEY: ${{ secrets.CENSUS_API_KEY }}

      # - name: Install npm
      #   uses: actions/setup-node@v1
      # 
      # - name: Deploy to Netlify
      #   # NETLIFY_AUTH_TOKEN and NETLIFY_SITE_ID added in the repo's secrets
      #   env:
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      #     NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      #   run: |
      #     npm install netlify-cli -g
      #     netlify deploy --prod --dir _book
      
      - uses: actions/upload-artifact@v1
        with:
          name: _book
          path: _book/

# Need to first create an empty gh-pages branch
# see https://pkgdown.r-lib.org/reference/deploy_site_github.html
# and also add secrets for a GH_PAT and EMAIL to the repository
# gh-action from Cecilapp/GitHub-Pages-deploy
  checkout-and-deploy:
   runs-on: ubuntu-latest
   needs: bookdown
   steps:
     - name: Checkout
       uses: actions/checkout@master
     - name: Download artifact
       uses: actions/download-artifact@v1.0.0
       with:
         # Artifact name
         name: _book # optional
         # Destination path
         path: _site # optional
     - name: Deploy to GitHub Pages
       uses: Cecilapp/GitHub-Pages-deploy@v3
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
         email: ${{ secrets.EMAIL }}
         build_dir: _site/
